# Generated by Django 5.2.4 on 2025-08-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('categorie', models.CharField(choices=[('anniversaire', 'Anniversaire'), ('mariage', 'Mariage'), ('dessert', 'Dessert'), ('autre', 'Autre')], max_length=20)),
                ('disponibilite', models.BooleanField(default=True)),
                ('avis', models.TextField(blank=True)),
            ],
        ),
    ]
