# Generated by Django 5.2.4 on 2025-08-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateau',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gateau',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gateaux/'),
        ),
    ]
