# Generated by Django 5.2.4 on 2025-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_remove_gateau_image_url_gateau_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateau',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
