# Generated by Django 5.2.4 on 2025-08-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_gateau_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateau',
            name='is_deleted',
        ),
    ]
