# Generated by Django 5.2.4 on 2025-08-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_remove_gateau_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateau',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
