# Generated by Django 5.2.4 on 2025-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur')], default='client', max_length=20),
        ),
    ]
